url: "https://biodockerfiles.github.io"
theme: null
analytics_id: G-3YHDBRD3B5

collections:
  dockerfiles:
    output: true
    permalink: /:name/
    sort_by: name
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "dockerfiles"
    values:
      is_dockerfile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      is_page: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

jekyll_compose:
  auto_open: false
  default_front_matter:
    dockerfiles:
      layout: default
      excerpt:
      website:
